Repository Particular/ServicePulse, pull requests merged in 2020-04, with the labels that each got.

#804 Better styling for Remove Endpoint icon
  src/ServicePulse.Host/app/css/particular.css
  src/ServicePulse.Host/app/js/views/endpoints/endpoints.html
Labels: Type: Improvement

#861 Prefixing view files for easier identification in editor
  src/ServicePulse.Host/app/js/views/about/about-view.html
  src/ServicePulse.Host/app/js/views/about/route.js
  src/ServicePulse.Host/app/js/views/archive/archive-view.html
  src/ServicePulse.Host/app/js/views/archive/route.js
  src/ServicePulse.Host/app/js/views/failed_groups/failed-groups-view.html
  src/ServicePulse.Host/app/js/views/failed_groups/route.js
  src/ServicePulse.Host/app/js/views/failed_messages/failed-messages-view.html
  src/ServicePulse.Host/app/js/views/failed_messages/route.js
  src/ServicePulse.Host/app/js/views/pending_retries/pending-retries-view.html
  src/ServicePulse.Host/app/js/views/pending_retries/route.js
Labels: Type: Improvement

#829 Update EULA to latest
  LICENSE.md
  src/Setup/res/License.rtf
Labels: Type: Improvement

#854 Prevent cached files from disrupting upgrade process
  src/ServicePulse.Host/app/index.html
  src/ServicePulse.Host/app/modules/modules.webpackconfig.js
  src/ServicePulse.Host/package-lock.json
  src/ServicePulse.Host/package.json
Labels: Type: Bug

#868 Update license messages
  src/ServicePulse.Host.Tests/tests/js/services/license.notifier.spec.js
  src/ServicePulse.Host.Tests/tests/js/views/failed_groups/controller.spec.js
  src/ServicePulse.Host/app/modules/configuration/views/license.html
  src/ServicePulse.Host/app/modules/shell/js/directives/platformTrialExpired.html
  src/ServicePulse.Host/app/modules/shell/js/licensenotifier/trialexpiring.html
Labels: Type: Improvement

#867 Add sort and filter to endpoints screen
  src/ServicePulse.Host/app/css/particular.css
  src/ServicePulse.Host/app/index.html
  src/ServicePulse.Host/app/js/views/endpoints/endpoints.controller.js
  src/ServicePulse.Host/app/js/views/endpoints/endpoints.html
Labels: Type: Feature

#877 Show the number of instances with connectivity problems on the monitoring overview screen
  src/ServicePulse.Host/app/css/particular.css
  src/ServicePulse.Host/app/index.html
  src/ServicePulse.Host/app/modules/monitoring/views/monitored_endpoints.html
Labels: Type: Feature
